AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NotificationEmail:
    Type: String
    Description: Email address to receive budget alerts.
  MonthlyBudget:
    Type: Number
    Description: (USD) Monthly budget in USD.
  AlertThreshold:
    Type: Number
    Description: (%) Alert when forecasted budget exceeds this percentage.
Description: Sets budget alerts
Resources:
  Budget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetLimit:
          Amount: !Ref MonthlyBudget
          Unit: USD
        BudgetName: Forecasted Monthly AWS Spend
        BudgetType: COST
        TimeUnit: MONTHLY
      NotificationsWithSubscribers:
        - Notification:
            ComparisonOperator: GREATER_THAN
            NotificationType: FORECASTED
            Threshold: !Ref AlertThreshold
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail
